<?php
$PUAPI_SERVER_URL="http://www.dnacrm.info/";
$PUAPI_LOGIN_PAGE="webservice.php";
$PUAPI_LOGIN_METHOD="post";
$PUAPI_CHALLENGE_PAGE="webservice.php";
$PUAPI_CHALLENGE_KEY=array("operation","username");
$PUAPI_LOGIN_POST_KEY=array("operation","username","accessKey");
$PUAPI_LOGIN_GET_KEY=array();
?>